#端口
server:
  port: 6010
  adminPath:
  # spring boot定时器默认同步执行 多线程执行修改这个配置 多少个定时器就修改多少
  threadSize: 4
  fileBasePath: /mnt/resource
  servlet:
    context-path: /

#数据库
spring:
  datasource:
    name: test
    url: jdbc:mysql://zhiguanzhuang.mysql.rds.aliyuncs.com:3306/nf_report?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: nf_report
    password: "Qr@20#$oon!"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  profiles:
    active: zjjconfig
  redis:
    database: 1
    timeout: 6000ms  # 连接超时时长（毫秒）
    password: zgz_pass4redis
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    sentinel:
      master: master
      nodes: 172.18.150.1:26379,172.18.150.2:26379


quanroon:
  rocketmq:
    producer:
      on-off: true
      name-server: 172.18.154.240:9876
      group-name: atten-prod
      topic: reportApi-prod

#mybatis
mybatis:
  type-aliases-package: com.quanroon.atten.reports.entity
  mapper-locations: "classpath*:mapper/**/*.xml"

socket:
  outTime:
    heartbeat: 300000
    signlog: 1000
#日志
logging:
  level:
    com: info

#jwt鉴权
jwt:
  secret: xx1WET12^%3^(WE45
  token-header:
    company: token
    proj: Authorization
  expire:
    company: 604800
    proj: 7200