package com.quanroon.atten.reports.entity.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UpPayrollInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public UpPayrollInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("proj_id is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("proj_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Integer value) {
            addCriterion("proj_id <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Integer value) {
            addCriterion("proj_id >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("proj_id >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Integer value) {
            addCriterion("proj_id <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Integer value) {
            addCriterion("proj_id <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Integer> values) {
            addCriterion("proj_id in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Integer> values) {
            addCriterion("proj_id not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Integer value1, Integer value2) {
            addCriterion("proj_id between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("proj_id not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateIsNull() {
            addCriterion("grant_salary_date is null");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateIsNotNull() {
            addCriterion("grant_salary_date is not null");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateEqualTo(Date value) {
            addCriterion("grant_salary_date =", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateNotEqualTo(Date value) {
            addCriterion("grant_salary_date <>", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateGreaterThan(Date value) {
            addCriterion("grant_salary_date >", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("grant_salary_date >=", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateLessThan(Date value) {
            addCriterion("grant_salary_date <", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateLessThanOrEqualTo(Date value) {
            addCriterion("grant_salary_date <=", value, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateIn(List<Date> values) {
            addCriterion("grant_salary_date in", values, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateNotIn(List<Date> values) {
            addCriterion("grant_salary_date not in", values, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateBetween(Date value1, Date value2) {
            addCriterion("grant_salary_date between", value1, value2, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantSalaryDateNotBetween(Date value1, Date value2) {
            addCriterion("grant_salary_date not between", value1, value2, "grantSalaryDate");
            return (Criteria) this;
        }

        public Criteria andGrantStatusIsNull() {
            addCriterion("grant_status is null");
            return (Criteria) this;
        }

        public Criteria andGrantStatusIsNotNull() {
            addCriterion("grant_status is not null");
            return (Criteria) this;
        }

        public Criteria andGrantStatusEqualTo(String value) {
            addCriterion("grant_status =", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotEqualTo(String value) {
            addCriterion("grant_status <>", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusGreaterThan(String value) {
            addCriterion("grant_status >", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusGreaterThanOrEqualTo(String value) {
            addCriterion("grant_status >=", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusLessThan(String value) {
            addCriterion("grant_status <", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusLessThanOrEqualTo(String value) {
            addCriterion("grant_status <=", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusLike(String value) {
            addCriterion("grant_status like", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotLike(String value) {
            addCriterion("grant_status not like", value, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusIn(List<String> values) {
            addCriterion("grant_status in", values, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotIn(List<String> values) {
            addCriterion("grant_status not in", values, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusBetween(String value1, String value2) {
            addCriterion("grant_status between", value1, value2, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andGrantStatusNotBetween(String value1, String value2) {
            addCriterion("grant_status not between", value1, value2, "grantStatus");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkIsNull() {
            addCriterion("confirm_mark is null");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkIsNotNull() {
            addCriterion("confirm_mark is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkEqualTo(String value) {
            addCriterion("confirm_mark =", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkNotEqualTo(String value) {
            addCriterion("confirm_mark <>", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkGreaterThan(String value) {
            addCriterion("confirm_mark >", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkGreaterThanOrEqualTo(String value) {
            addCriterion("confirm_mark >=", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkLessThan(String value) {
            addCriterion("confirm_mark <", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkLessThanOrEqualTo(String value) {
            addCriterion("confirm_mark <=", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkLike(String value) {
            addCriterion("confirm_mark like", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkNotLike(String value) {
            addCriterion("confirm_mark not like", value, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkIn(List<String> values) {
            addCriterion("confirm_mark in", values, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkNotIn(List<String> values) {
            addCriterion("confirm_mark not in", values, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkBetween(String value1, String value2) {
            addCriterion("confirm_mark between", value1, value2, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andConfirmMarkNotBetween(String value1, String value2) {
            addCriterion("confirm_mark not between", value1, value2, "confirmMark");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNull() {
            addCriterion("report_code is null");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNotNull() {
            addCriterion("report_code is not null");
            return (Criteria) this;
        }

        public Criteria andReportCodeEqualTo(String value) {
            addCriterion("report_code =", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotEqualTo(String value) {
            addCriterion("report_code <>", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThan(String value) {
            addCriterion("report_code >", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("report_code >=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThan(String value) {
            addCriterion("report_code <", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThanOrEqualTo(String value) {
            addCriterion("report_code <=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLike(String value) {
            addCriterion("report_code like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotLike(String value) {
            addCriterion("report_code not like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeIn(List<String> values) {
            addCriterion("report_code in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotIn(List<String> values) {
            addCriterion("report_code not in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeBetween(String value1, String value2) {
            addCriterion("report_code between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotBetween(String value1, String value2) {
            addCriterion("report_code not between", value1, value2, "reportCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_payroll_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 29 15:05:03 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}