package com.quanroon.atten.reports.entity.example;

import java.util.ArrayList;
import java.util.List;

public class UpParamsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public UpParamsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("proj_id is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("proj_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Integer value) {
            addCriterion("proj_id <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Integer value) {
            addCriterion("proj_id >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("proj_id >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Integer value) {
            addCriterion("proj_id <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Integer value) {
            addCriterion("proj_id <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Integer> values) {
            addCriterion("proj_id in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Integer> values) {
            addCriterion("proj_id not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Integer value1, Integer value2) {
            addCriterion("proj_id between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("proj_id not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andPaawordIsNull() {
            addCriterion("paaword is null");
            return (Criteria) this;
        }

        public Criteria andPaawordIsNotNull() {
            addCriterion("paaword is not null");
            return (Criteria) this;
        }

        public Criteria andPaawordEqualTo(String value) {
            addCriterion("paaword =", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordNotEqualTo(String value) {
            addCriterion("paaword <>", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordGreaterThan(String value) {
            addCriterion("paaword >", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordGreaterThanOrEqualTo(String value) {
            addCriterion("paaword >=", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordLessThan(String value) {
            addCriterion("paaword <", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordLessThanOrEqualTo(String value) {
            addCriterion("paaword <=", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordLike(String value) {
            addCriterion("paaword like", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordNotLike(String value) {
            addCriterion("paaword not like", value, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordIn(List<String> values) {
            addCriterion("paaword in", values, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordNotIn(List<String> values) {
            addCriterion("paaword not in", values, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordBetween(String value1, String value2) {
            addCriterion("paaword between", value1, value2, "paaword");
            return (Criteria) this;
        }

        public Criteria andPaawordNotBetween(String value1, String value2) {
            addCriterion("paaword not between", value1, value2, "paaword");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNull() {
            addCriterion("project_code is null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNotNull() {
            addCriterion("project_code is not null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeEqualTo(String value) {
            addCriterion("project_code =", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotEqualTo(String value) {
            addCriterion("project_code <>", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThan(String value) {
            addCriterion("project_code >", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("project_code >=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThan(String value) {
            addCriterion("project_code <", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThanOrEqualTo(String value) {
            addCriterion("project_code <=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLike(String value) {
            addCriterion("project_code like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotLike(String value) {
            addCriterion("project_code not like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIn(List<String> values) {
            addCriterion("project_code in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotIn(List<String> values) {
            addCriterion("project_code not in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeBetween(String value1, String value2) {
            addCriterion("project_code between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotBetween(String value1, String value2) {
            addCriterion("project_code not between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andKeyIsNull() {
            addCriterion("key is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("key is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("key =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("key <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("key >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("key >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("key <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("key <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("key like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("key not like", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<String> values) {
            addCriterion("key in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<String> values) {
            addCriterion("key not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("key between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("key not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andSecrectIsNull() {
            addCriterion("secrect is null");
            return (Criteria) this;
        }

        public Criteria andSecrectIsNotNull() {
            addCriterion("secrect is not null");
            return (Criteria) this;
        }

        public Criteria andSecrectEqualTo(String value) {
            addCriterion("secrect =", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectNotEqualTo(String value) {
            addCriterion("secrect <>", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectGreaterThan(String value) {
            addCriterion("secrect >", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectGreaterThanOrEqualTo(String value) {
            addCriterion("secrect >=", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectLessThan(String value) {
            addCriterion("secrect <", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectLessThanOrEqualTo(String value) {
            addCriterion("secrect <=", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectLike(String value) {
            addCriterion("secrect like", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectNotLike(String value) {
            addCriterion("secrect not like", value, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectIn(List<String> values) {
            addCriterion("secrect in", values, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectNotIn(List<String> values) {
            addCriterion("secrect not in", values, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectBetween(String value1, String value2) {
            addCriterion("secrect between", value1, value2, "secrect");
            return (Criteria) this;
        }

        public Criteria andSecrectNotBetween(String value1, String value2) {
            addCriterion("secrect not between", value1, value2, "secrect");
            return (Criteria) this;
        }

        public Criteria andCollectKeyIsNull() {
            addCriterion("collect_key is null");
            return (Criteria) this;
        }

        public Criteria andCollectKeyIsNotNull() {
            addCriterion("collect_key is not null");
            return (Criteria) this;
        }

        public Criteria andCollectKeyEqualTo(String value) {
            addCriterion("collect_key =", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyNotEqualTo(String value) {
            addCriterion("collect_key <>", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyGreaterThan(String value) {
            addCriterion("collect_key >", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("collect_key >=", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyLessThan(String value) {
            addCriterion("collect_key <", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyLessThanOrEqualTo(String value) {
            addCriterion("collect_key <=", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyLike(String value) {
            addCriterion("collect_key like", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyNotLike(String value) {
            addCriterion("collect_key not like", value, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyIn(List<String> values) {
            addCriterion("collect_key in", values, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyNotIn(List<String> values) {
            addCriterion("collect_key not in", values, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyBetween(String value1, String value2) {
            addCriterion("collect_key between", value1, value2, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectKeyNotBetween(String value1, String value2) {
            addCriterion("collect_key not between", value1, value2, "collectKey");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectIsNull() {
            addCriterion("collect_secrect is null");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectIsNotNull() {
            addCriterion("collect_secrect is not null");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectEqualTo(String value) {
            addCriterion("collect_secrect =", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectNotEqualTo(String value) {
            addCriterion("collect_secrect <>", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectGreaterThan(String value) {
            addCriterion("collect_secrect >", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectGreaterThanOrEqualTo(String value) {
            addCriterion("collect_secrect >=", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectLessThan(String value) {
            addCriterion("collect_secrect <", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectLessThanOrEqualTo(String value) {
            addCriterion("collect_secrect <=", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectLike(String value) {
            addCriterion("collect_secrect like", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectNotLike(String value) {
            addCriterion("collect_secrect not like", value, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectIn(List<String> values) {
            addCriterion("collect_secrect in", values, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectNotIn(List<String> values) {
            addCriterion("collect_secrect not in", values, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectBetween(String value1, String value2) {
            addCriterion("collect_secrect between", value1, value2, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andCollectSecrectNotBetween(String value1, String value2) {
            addCriterion("collect_secrect not between", value1, value2, "collectSecrect");
            return (Criteria) this;
        }

        public Criteria andAppTokenIsNull() {
            addCriterion("app_token is null");
            return (Criteria) this;
        }

        public Criteria andAppTokenIsNotNull() {
            addCriterion("app_token is not null");
            return (Criteria) this;
        }

        public Criteria andAppTokenEqualTo(String value) {
            addCriterion("app_token =", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotEqualTo(String value) {
            addCriterion("app_token <>", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenGreaterThan(String value) {
            addCriterion("app_token >", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenGreaterThanOrEqualTo(String value) {
            addCriterion("app_token >=", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLessThan(String value) {
            addCriterion("app_token <", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLessThanOrEqualTo(String value) {
            addCriterion("app_token <=", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLike(String value) {
            addCriterion("app_token like", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotLike(String value) {
            addCriterion("app_token not like", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenIn(List<String> values) {
            addCriterion("app_token in", values, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotIn(List<String> values) {
            addCriterion("app_token not in", values, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenBetween(String value1, String value2) {
            addCriterion("app_token between", value1, value2, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotBetween(String value1, String value2) {
            addCriterion("app_token not between", value1, value2, "appToken");
            return (Criteria) this;
        }

        public Criteria andUpProvinceIsNull() {
            addCriterion("up_province is null");
            return (Criteria) this;
        }

        public Criteria andUpProvinceIsNotNull() {
            addCriterion("up_province is not null");
            return (Criteria) this;
        }

        public Criteria andUpProvinceEqualTo(String value) {
            addCriterion("up_province =", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceNotEqualTo(String value) {
            addCriterion("up_province <>", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceGreaterThan(String value) {
            addCriterion("up_province >", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("up_province >=", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceLessThan(String value) {
            addCriterion("up_province <", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceLessThanOrEqualTo(String value) {
            addCriterion("up_province <=", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceLike(String value) {
            addCriterion("up_province like", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceNotLike(String value) {
            addCriterion("up_province not like", value, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceIn(List<String> values) {
            addCriterion("up_province in", values, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceNotIn(List<String> values) {
            addCriterion("up_province not in", values, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceBetween(String value1, String value2) {
            addCriterion("up_province between", value1, value2, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpProvinceNotBetween(String value1, String value2) {
            addCriterion("up_province not between", value1, value2, "upProvince");
            return (Criteria) this;
        }

        public Criteria andUpCityIsNull() {
            addCriterion("up_city is null");
            return (Criteria) this;
        }

        public Criteria andUpCityIsNotNull() {
            addCriterion("up_city is not null");
            return (Criteria) this;
        }

        public Criteria andUpCityEqualTo(String value) {
            addCriterion("up_city =", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityNotEqualTo(String value) {
            addCriterion("up_city <>", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityGreaterThan(String value) {
            addCriterion("up_city >", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityGreaterThanOrEqualTo(String value) {
            addCriterion("up_city >=", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityLessThan(String value) {
            addCriterion("up_city <", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityLessThanOrEqualTo(String value) {
            addCriterion("up_city <=", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityLike(String value) {
            addCriterion("up_city like", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityNotLike(String value) {
            addCriterion("up_city not like", value, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityIn(List<String> values) {
            addCriterion("up_city in", values, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityNotIn(List<String> values) {
            addCriterion("up_city not in", values, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityBetween(String value1, String value2) {
            addCriterion("up_city between", value1, value2, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpCityNotBetween(String value1, String value2) {
            addCriterion("up_city not between", value1, value2, "upCity");
            return (Criteria) this;
        }

        public Criteria andUpAreaIsNull() {
            addCriterion("up_area is null");
            return (Criteria) this;
        }

        public Criteria andUpAreaIsNotNull() {
            addCriterion("up_area is not null");
            return (Criteria) this;
        }

        public Criteria andUpAreaEqualTo(String value) {
            addCriterion("up_area =", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaNotEqualTo(String value) {
            addCriterion("up_area <>", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaGreaterThan(String value) {
            addCriterion("up_area >", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaGreaterThanOrEqualTo(String value) {
            addCriterion("up_area >=", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaLessThan(String value) {
            addCriterion("up_area <", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaLessThanOrEqualTo(String value) {
            addCriterion("up_area <=", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaLike(String value) {
            addCriterion("up_area like", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaNotLike(String value) {
            addCriterion("up_area not like", value, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaIn(List<String> values) {
            addCriterion("up_area in", values, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaNotIn(List<String> values) {
            addCriterion("up_area not in", values, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaBetween(String value1, String value2) {
            addCriterion("up_area between", value1, value2, "upArea");
            return (Criteria) this;
        }

        public Criteria andUpAreaNotBetween(String value1, String value2) {
            addCriterion("up_area not between", value1, value2, "upArea");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_params
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 29 15:04:12 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}