package com.quanroon.atten.reports.entity.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UpWorkerInExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public UpWorkerInExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjIdIsNull() {
            addCriterion("proj_id is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("proj_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Integer value) {
            addCriterion("proj_id <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Integer value) {
            addCriterion("proj_id >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("proj_id >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Integer value) {
            addCriterion("proj_id <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Integer value) {
            addCriterion("proj_id <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Integer> values) {
            addCriterion("proj_id in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Integer> values) {
            addCriterion("proj_id not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Integer value1, Integer value2) {
            addCriterion("proj_id between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Integer value1, Integer value2) {
            addCriterion("proj_id not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdIsNull() {
            addCriterion("worker_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkerIdIsNotNull() {
            addCriterion("worker_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkerIdEqualTo(Integer value) {
            addCriterion("worker_id =", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdNotEqualTo(Integer value) {
            addCriterion("worker_id <>", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdGreaterThan(Integer value) {
            addCriterion("worker_id >", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("worker_id >=", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdLessThan(Integer value) {
            addCriterion("worker_id <", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdLessThanOrEqualTo(Integer value) {
            addCriterion("worker_id <=", value, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdIn(List<Integer> values) {
            addCriterion("worker_id in", values, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdNotIn(List<Integer> values) {
            addCriterion("worker_id not in", values, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdBetween(Integer value1, Integer value2) {
            addCriterion("worker_id between", value1, value2, "workerId");
            return (Criteria) this;
        }

        public Criteria andWorkerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("worker_id not between", value1, value2, "workerId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andEntryDateIsNull() {
            addCriterion("entry_date is null");
            return (Criteria) this;
        }

        public Criteria andEntryDateIsNotNull() {
            addCriterion("entry_date is not null");
            return (Criteria) this;
        }

        public Criteria andEntryDateEqualTo(Date value) {
            addCriterion("entry_date =", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotEqualTo(Date value) {
            addCriterion("entry_date <>", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateGreaterThan(Date value) {
            addCriterion("entry_date >", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("entry_date >=", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateLessThan(Date value) {
            addCriterion("entry_date <", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateLessThanOrEqualTo(Date value) {
            addCriterion("entry_date <=", value, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateIn(List<Date> values) {
            addCriterion("entry_date in", values, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotIn(List<Date> values) {
            addCriterion("entry_date not in", values, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateBetween(Date value1, Date value2) {
            addCriterion("entry_date between", value1, value2, "entryDate");
            return (Criteria) this;
        }

        public Criteria andEntryDateNotBetween(Date value1, Date value2) {
            addCriterion("entry_date not between", value1, value2, "entryDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateIsNull() {
            addCriterion("leave_date is null");
            return (Criteria) this;
        }

        public Criteria andLeaveDateIsNotNull() {
            addCriterion("leave_date is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveDateEqualTo(Date value) {
            addCriterion("leave_date =", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateNotEqualTo(Date value) {
            addCriterion("leave_date <>", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateGreaterThan(Date value) {
            addCriterion("leave_date >", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("leave_date >=", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateLessThan(Date value) {
            addCriterion("leave_date <", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateLessThanOrEqualTo(Date value) {
            addCriterion("leave_date <=", value, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateIn(List<Date> values) {
            addCriterion("leave_date in", values, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateNotIn(List<Date> values) {
            addCriterion("leave_date not in", values, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateBetween(Date value1, Date value2) {
            addCriterion("leave_date between", value1, value2, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andLeaveDateNotBetween(Date value1, Date value2) {
            addCriterion("leave_date not between", value1, value2, "leaveDate");
            return (Criteria) this;
        }

        public Criteria andEgyContactIsNull() {
            addCriterion("egy_contact is null");
            return (Criteria) this;
        }

        public Criteria andEgyContactIsNotNull() {
            addCriterion("egy_contact is not null");
            return (Criteria) this;
        }

        public Criteria andEgyContactEqualTo(String value) {
            addCriterion("egy_contact =", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactNotEqualTo(String value) {
            addCriterion("egy_contact <>", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactGreaterThan(String value) {
            addCriterion("egy_contact >", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactGreaterThanOrEqualTo(String value) {
            addCriterion("egy_contact >=", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactLessThan(String value) {
            addCriterion("egy_contact <", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactLessThanOrEqualTo(String value) {
            addCriterion("egy_contact <=", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactLike(String value) {
            addCriterion("egy_contact like", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactNotLike(String value) {
            addCriterion("egy_contact not like", value, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactIn(List<String> values) {
            addCriterion("egy_contact in", values, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactNotIn(List<String> values) {
            addCriterion("egy_contact not in", values, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactBetween(String value1, String value2) {
            addCriterion("egy_contact between", value1, value2, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactNotBetween(String value1, String value2) {
            addCriterion("egy_contact not between", value1, value2, "egyContact");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneIsNull() {
            addCriterion("egy_contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneIsNotNull() {
            addCriterion("egy_contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneEqualTo(String value) {
            addCriterion("egy_contact_phone =", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneNotEqualTo(String value) {
            addCriterion("egy_contact_phone <>", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneGreaterThan(String value) {
            addCriterion("egy_contact_phone >", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("egy_contact_phone >=", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneLessThan(String value) {
            addCriterion("egy_contact_phone <", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("egy_contact_phone <=", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneLike(String value) {
            addCriterion("egy_contact_phone like", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneNotLike(String value) {
            addCriterion("egy_contact_phone not like", value, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneIn(List<String> values) {
            addCriterion("egy_contact_phone in", values, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneNotIn(List<String> values) {
            addCriterion("egy_contact_phone not in", values, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneBetween(String value1, String value2) {
            addCriterion("egy_contact_phone between", value1, value2, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andEgyContactPhoneNotBetween(String value1, String value2) {
            addCriterion("egy_contact_phone not between", value1, value2, "egyContactPhone");
            return (Criteria) this;
        }

        public Criteria andIsForemanIsNull() {
            addCriterion("is_foreman is null");
            return (Criteria) this;
        }

        public Criteria andIsForemanIsNotNull() {
            addCriterion("is_foreman is not null");
            return (Criteria) this;
        }

        public Criteria andIsForemanEqualTo(String value) {
            addCriterion("is_foreman =", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanNotEqualTo(String value) {
            addCriterion("is_foreman <>", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanGreaterThan(String value) {
            addCriterion("is_foreman >", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanGreaterThanOrEqualTo(String value) {
            addCriterion("is_foreman >=", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanLessThan(String value) {
            addCriterion("is_foreman <", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanLessThanOrEqualTo(String value) {
            addCriterion("is_foreman <=", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanLike(String value) {
            addCriterion("is_foreman like", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanNotLike(String value) {
            addCriterion("is_foreman not like", value, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanIn(List<String> values) {
            addCriterion("is_foreman in", values, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanNotIn(List<String> values) {
            addCriterion("is_foreman not in", values, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanBetween(String value1, String value2) {
            addCriterion("is_foreman between", value1, value2, "isForeman");
            return (Criteria) this;
        }

        public Criteria andIsForemanNotBetween(String value1, String value2) {
            addCriterion("is_foreman not between", value1, value2, "isForeman");
            return (Criteria) this;
        }

        public Criteria andContractNumberIsNull() {
            addCriterion("contract_number is null");
            return (Criteria) this;
        }

        public Criteria andContractNumberIsNotNull() {
            addCriterion("contract_number is not null");
            return (Criteria) this;
        }

        public Criteria andContractNumberEqualTo(String value) {
            addCriterion("contract_number =", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberNotEqualTo(String value) {
            addCriterion("contract_number <>", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberGreaterThan(String value) {
            addCriterion("contract_number >", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberGreaterThanOrEqualTo(String value) {
            addCriterion("contract_number >=", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberLessThan(String value) {
            addCriterion("contract_number <", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberLessThanOrEqualTo(String value) {
            addCriterion("contract_number <=", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberLike(String value) {
            addCriterion("contract_number like", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberNotLike(String value) {
            addCriterion("contract_number not like", value, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberIn(List<String> values) {
            addCriterion("contract_number in", values, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberNotIn(List<String> values) {
            addCriterion("contract_number not in", values, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberBetween(String value1, String value2) {
            addCriterion("contract_number between", value1, value2, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractNumberNotBetween(String value1, String value2) {
            addCriterion("contract_number not between", value1, value2, "contractNumber");
            return (Criteria) this;
        }

        public Criteria andContractSignDateIsNull() {
            addCriterion("contract_sign_date is null");
            return (Criteria) this;
        }

        public Criteria andContractSignDateIsNotNull() {
            addCriterion("contract_sign_date is not null");
            return (Criteria) this;
        }

        public Criteria andContractSignDateEqualTo(Date value) {
            addCriterion("contract_sign_date =", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateNotEqualTo(Date value) {
            addCriterion("contract_sign_date <>", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateGreaterThan(Date value) {
            addCriterion("contract_sign_date >", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_sign_date >=", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateLessThan(Date value) {
            addCriterion("contract_sign_date <", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateLessThanOrEqualTo(Date value) {
            addCriterion("contract_sign_date <=", value, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateIn(List<Date> values) {
            addCriterion("contract_sign_date in", values, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateNotIn(List<Date> values) {
            addCriterion("contract_sign_date not in", values, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateBetween(Date value1, Date value2) {
            addCriterion("contract_sign_date between", value1, value2, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractSignDateNotBetween(Date value1, Date value2) {
            addCriterion("contract_sign_date not between", value1, value2, "contractSignDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateIsNull() {
            addCriterion("contract_start_date is null");
            return (Criteria) this;
        }

        public Criteria andContractStartDateIsNotNull() {
            addCriterion("contract_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andContractStartDateEqualTo(Date value) {
            addCriterion("contract_start_date =", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateNotEqualTo(Date value) {
            addCriterion("contract_start_date <>", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateGreaterThan(Date value) {
            addCriterion("contract_start_date >", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_start_date >=", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateLessThan(Date value) {
            addCriterion("contract_start_date <", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateLessThanOrEqualTo(Date value) {
            addCriterion("contract_start_date <=", value, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateIn(List<Date> values) {
            addCriterion("contract_start_date in", values, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateNotIn(List<Date> values) {
            addCriterion("contract_start_date not in", values, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateBetween(Date value1, Date value2) {
            addCriterion("contract_start_date between", value1, value2, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractStartDateNotBetween(Date value1, Date value2) {
            addCriterion("contract_start_date not between", value1, value2, "contractStartDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIsNull() {
            addCriterion("contract_end_date is null");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIsNotNull() {
            addCriterion("contract_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andContractEndDateEqualTo(Date value) {
            addCriterion("contract_end_date =", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotEqualTo(Date value) {
            addCriterion("contract_end_date <>", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateGreaterThan(Date value) {
            addCriterion("contract_end_date >", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_end_date >=", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateLessThan(Date value) {
            addCriterion("contract_end_date <", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateLessThanOrEqualTo(Date value) {
            addCriterion("contract_end_date <=", value, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateIn(List<Date> values) {
            addCriterion("contract_end_date in", values, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotIn(List<Date> values) {
            addCriterion("contract_end_date not in", values, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateBetween(Date value1, Date value2) {
            addCriterion("contract_end_date between", value1, value2, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractEndDateNotBetween(Date value1, Date value2) {
            addCriterion("contract_end_date not between", value1, value2, "contractEndDate");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeIsNull() {
            addCriterion("contract_limit_type is null");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeIsNotNull() {
            addCriterion("contract_limit_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeEqualTo(String value) {
            addCriterion("contract_limit_type =", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeNotEqualTo(String value) {
            addCriterion("contract_limit_type <>", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeGreaterThan(String value) {
            addCriterion("contract_limit_type >", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_limit_type >=", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeLessThan(String value) {
            addCriterion("contract_limit_type <", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeLessThanOrEqualTo(String value) {
            addCriterion("contract_limit_type <=", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeLike(String value) {
            addCriterion("contract_limit_type like", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeNotLike(String value) {
            addCriterion("contract_limit_type not like", value, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeIn(List<String> values) {
            addCriterion("contract_limit_type in", values, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeNotIn(List<String> values) {
            addCriterion("contract_limit_type not in", values, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeBetween(String value1, String value2) {
            addCriterion("contract_limit_type between", value1, value2, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andContractLimitTypeNotBetween(String value1, String value2) {
            addCriterion("contract_limit_type not between", value1, value2, "contractLimitType");
            return (Criteria) this;
        }

        public Criteria andSalaryWayIsNull() {
            addCriterion("salary_way is null");
            return (Criteria) this;
        }

        public Criteria andSalaryWayIsNotNull() {
            addCriterion("salary_way is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryWayEqualTo(String value) {
            addCriterion("salary_way =", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayNotEqualTo(String value) {
            addCriterion("salary_way <>", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayGreaterThan(String value) {
            addCriterion("salary_way >", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayGreaterThanOrEqualTo(String value) {
            addCriterion("salary_way >=", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayLessThan(String value) {
            addCriterion("salary_way <", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayLessThanOrEqualTo(String value) {
            addCriterion("salary_way <=", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayLike(String value) {
            addCriterion("salary_way like", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayNotLike(String value) {
            addCriterion("salary_way not like", value, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayIn(List<String> values) {
            addCriterion("salary_way in", values, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayNotIn(List<String> values) {
            addCriterion("salary_way not in", values, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayBetween(String value1, String value2) {
            addCriterion("salary_way between", value1, value2, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andSalaryWayNotBetween(String value1, String value2) {
            addCriterion("salary_way not between", value1, value2, "salaryWay");
            return (Criteria) this;
        }

        public Criteria andPayDayIsNull() {
            addCriterion("pay_day is null");
            return (Criteria) this;
        }

        public Criteria andPayDayIsNotNull() {
            addCriterion("pay_day is not null");
            return (Criteria) this;
        }

        public Criteria andPayDayEqualTo(Integer value) {
            addCriterion("pay_day =", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayNotEqualTo(Integer value) {
            addCriterion("pay_day <>", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayGreaterThan(Integer value) {
            addCriterion("pay_day >", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_day >=", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayLessThan(Integer value) {
            addCriterion("pay_day <", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayLessThanOrEqualTo(Integer value) {
            addCriterion("pay_day <=", value, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayIn(List<Integer> values) {
            addCriterion("pay_day in", values, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayNotIn(List<Integer> values) {
            addCriterion("pay_day not in", values, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayBetween(Integer value1, Integer value2) {
            addCriterion("pay_day between", value1, value2, "payDay");
            return (Criteria) this;
        }

        public Criteria andPayDayNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_day not between", value1, value2, "payDay");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyIsNull() {
            addCriterion("salary_money is null");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyIsNotNull() {
            addCriterion("salary_money is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyEqualTo(BigDecimal value) {
            addCriterion("salary_money =", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyNotEqualTo(BigDecimal value) {
            addCriterion("salary_money <>", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyGreaterThan(BigDecimal value) {
            addCriterion("salary_money >", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("salary_money >=", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyLessThan(BigDecimal value) {
            addCriterion("salary_money <", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("salary_money <=", value, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyIn(List<BigDecimal> values) {
            addCriterion("salary_money in", values, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyNotIn(List<BigDecimal> values) {
            addCriterion("salary_money not in", values, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salary_money between", value1, value2, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salary_money not between", value1, value2, "salaryMoney");
            return (Criteria) this;
        }

        public Criteria andSalaryBankIsNull() {
            addCriterion("salary_bank is null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankIsNotNull() {
            addCriterion("salary_bank is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankEqualTo(String value) {
            addCriterion("salary_bank =", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNotEqualTo(String value) {
            addCriterion("salary_bank <>", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankGreaterThan(String value) {
            addCriterion("salary_bank >", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankGreaterThanOrEqualTo(String value) {
            addCriterion("salary_bank >=", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankLessThan(String value) {
            addCriterion("salary_bank <", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankLessThanOrEqualTo(String value) {
            addCriterion("salary_bank <=", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankLike(String value) {
            addCriterion("salary_bank like", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNotLike(String value) {
            addCriterion("salary_bank not like", value, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankIn(List<String> values) {
            addCriterion("salary_bank in", values, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNotIn(List<String> values) {
            addCriterion("salary_bank not in", values, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBetween(String value1, String value2) {
            addCriterion("salary_bank between", value1, value2, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNotBetween(String value1, String value2) {
            addCriterion("salary_bank not between", value1, value2, "salaryBank");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoIsNull() {
            addCriterion("salary_bank_no is null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoIsNotNull() {
            addCriterion("salary_bank_no is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoEqualTo(String value) {
            addCriterion("salary_bank_no =", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoNotEqualTo(String value) {
            addCriterion("salary_bank_no <>", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoGreaterThan(String value) {
            addCriterion("salary_bank_no >", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoGreaterThanOrEqualTo(String value) {
            addCriterion("salary_bank_no >=", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoLessThan(String value) {
            addCriterion("salary_bank_no <", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoLessThanOrEqualTo(String value) {
            addCriterion("salary_bank_no <=", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoLike(String value) {
            addCriterion("salary_bank_no like", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoNotLike(String value) {
            addCriterion("salary_bank_no not like", value, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoIn(List<String> values) {
            addCriterion("salary_bank_no in", values, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoNotIn(List<String> values) {
            addCriterion("salary_bank_no not in", values, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoBetween(String value1, String value2) {
            addCriterion("salary_bank_no between", value1, value2, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankNoNotBetween(String value1, String value2) {
            addCriterion("salary_bank_no not between", value1, value2, "salaryBankNo");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchIsNull() {
            addCriterion("salary_bank_branch is null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchIsNotNull() {
            addCriterion("salary_bank_branch is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchEqualTo(String value) {
            addCriterion("salary_bank_branch =", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchNotEqualTo(String value) {
            addCriterion("salary_bank_branch <>", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchGreaterThan(String value) {
            addCriterion("salary_bank_branch >", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchGreaterThanOrEqualTo(String value) {
            addCriterion("salary_bank_branch >=", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchLessThan(String value) {
            addCriterion("salary_bank_branch <", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchLessThanOrEqualTo(String value) {
            addCriterion("salary_bank_branch <=", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchLike(String value) {
            addCriterion("salary_bank_branch like", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchNotLike(String value) {
            addCriterion("salary_bank_branch not like", value, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchIn(List<String> values) {
            addCriterion("salary_bank_branch in", values, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchNotIn(List<String> values) {
            addCriterion("salary_bank_branch not in", values, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchBetween(String value1, String value2) {
            addCriterion("salary_bank_branch between", value1, value2, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andSalaryBankBranchNotBetween(String value1, String value2) {
            addCriterion("salary_bank_branch not between", value1, value2, "salaryBankBranch");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIsNull() {
            addCriterion("member_type is null");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIsNotNull() {
            addCriterion("member_type is not null");
            return (Criteria) this;
        }

        public Criteria andMemberTypeEqualTo(String value) {
            addCriterion("member_type =", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotEqualTo(String value) {
            addCriterion("member_type <>", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeGreaterThan(String value) {
            addCriterion("member_type >", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeGreaterThanOrEqualTo(String value) {
            addCriterion("member_type >=", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeLessThan(String value) {
            addCriterion("member_type <", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeLessThanOrEqualTo(String value) {
            addCriterion("member_type <=", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeLike(String value) {
            addCriterion("member_type like", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotLike(String value) {
            addCriterion("member_type not like", value, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeIn(List<String> values) {
            addCriterion("member_type in", values, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotIn(List<String> values) {
            addCriterion("member_type not in", values, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeBetween(String value1, String value2) {
            addCriterion("member_type between", value1, value2, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberTypeNotBetween(String value1, String value2) {
            addCriterion("member_type not between", value1, value2, "memberType");
            return (Criteria) this;
        }

        public Criteria andMemberRoleIsNull() {
            addCriterion("member_role is null");
            return (Criteria) this;
        }

        public Criteria andMemberRoleIsNotNull() {
            addCriterion("member_role is not null");
            return (Criteria) this;
        }

        public Criteria andMemberRoleEqualTo(String value) {
            addCriterion("member_role =", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleNotEqualTo(String value) {
            addCriterion("member_role <>", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleGreaterThan(String value) {
            addCriterion("member_role >", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleGreaterThanOrEqualTo(String value) {
            addCriterion("member_role >=", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleLessThan(String value) {
            addCriterion("member_role <", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleLessThanOrEqualTo(String value) {
            addCriterion("member_role <=", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleLike(String value) {
            addCriterion("member_role like", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleNotLike(String value) {
            addCriterion("member_role not like", value, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleIn(List<String> values) {
            addCriterion("member_role in", values, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleNotIn(List<String> values) {
            addCriterion("member_role not in", values, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleBetween(String value1, String value2) {
            addCriterion("member_role between", value1, value2, "memberRole");
            return (Criteria) this;
        }

        public Criteria andMemberRoleNotBetween(String value1, String value2) {
            addCriterion("member_role not between", value1, value2, "memberRole");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("work_type is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("work_type is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(String value) {
            addCriterion("work_type =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(String value) {
            addCriterion("work_type <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(String value) {
            addCriterion("work_type >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("work_type >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(String value) {
            addCriterion("work_type <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("work_type <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLike(String value) {
            addCriterion("work_type like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotLike(String value) {
            addCriterion("work_type not like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<String> values) {
            addCriterion("work_type in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<String> values) {
            addCriterion("work_type not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(String value1, String value2) {
            addCriterion("work_type between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(String value1, String value2) {
            addCriterion("work_type not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceIsNull() {
            addCriterion("is_medical_insurance is null");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceIsNotNull() {
            addCriterion("is_medical_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceEqualTo(String value) {
            addCriterion("is_medical_insurance =", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceNotEqualTo(String value) {
            addCriterion("is_medical_insurance <>", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceGreaterThan(String value) {
            addCriterion("is_medical_insurance >", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("is_medical_insurance >=", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceLessThan(String value) {
            addCriterion("is_medical_insurance <", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceLessThanOrEqualTo(String value) {
            addCriterion("is_medical_insurance <=", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceLike(String value) {
            addCriterion("is_medical_insurance like", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceNotLike(String value) {
            addCriterion("is_medical_insurance not like", value, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceIn(List<String> values) {
            addCriterion("is_medical_insurance in", values, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceNotIn(List<String> values) {
            addCriterion("is_medical_insurance not in", values, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceBetween(String value1, String value2) {
            addCriterion("is_medical_insurance between", value1, value2, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsMedicalInsuranceNotBetween(String value1, String value2) {
            addCriterion("is_medical_insurance not between", value1, value2, "isMedicalInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceIsNull() {
            addCriterion("is_endowment_insurance is null");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceIsNotNull() {
            addCriterion("is_endowment_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceEqualTo(String value) {
            addCriterion("is_endowment_insurance =", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceNotEqualTo(String value) {
            addCriterion("is_endowment_insurance <>", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceGreaterThan(String value) {
            addCriterion("is_endowment_insurance >", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("is_endowment_insurance >=", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceLessThan(String value) {
            addCriterion("is_endowment_insurance <", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceLessThanOrEqualTo(String value) {
            addCriterion("is_endowment_insurance <=", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceLike(String value) {
            addCriterion("is_endowment_insurance like", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceNotLike(String value) {
            addCriterion("is_endowment_insurance not like", value, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceIn(List<String> values) {
            addCriterion("is_endowment_insurance in", values, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceNotIn(List<String> values) {
            addCriterion("is_endowment_insurance not in", values, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceBetween(String value1, String value2) {
            addCriterion("is_endowment_insurance between", value1, value2, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEndowmentInsuranceNotBetween(String value1, String value2) {
            addCriterion("is_endowment_insurance not between", value1, value2, "isEndowmentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceIsNull() {
            addCriterion("is_employ_insurance is null");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceIsNotNull() {
            addCriterion("is_employ_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceEqualTo(String value) {
            addCriterion("is_employ_insurance =", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceNotEqualTo(String value) {
            addCriterion("is_employ_insurance <>", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceGreaterThan(String value) {
            addCriterion("is_employ_insurance >", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("is_employ_insurance >=", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceLessThan(String value) {
            addCriterion("is_employ_insurance <", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceLessThanOrEqualTo(String value) {
            addCriterion("is_employ_insurance <=", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceLike(String value) {
            addCriterion("is_employ_insurance like", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceNotLike(String value) {
            addCriterion("is_employ_insurance not like", value, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceIn(List<String> values) {
            addCriterion("is_employ_insurance in", values, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceNotIn(List<String> values) {
            addCriterion("is_employ_insurance not in", values, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceBetween(String value1, String value2) {
            addCriterion("is_employ_insurance between", value1, value2, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsEmployInsuranceNotBetween(String value1, String value2) {
            addCriterion("is_employ_insurance not between", value1, value2, "isEmployInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceIsNull() {
            addCriterion("is_accident_insurance is null");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceIsNotNull() {
            addCriterion("is_accident_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceEqualTo(String value) {
            addCriterion("is_accident_insurance =", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceNotEqualTo(String value) {
            addCriterion("is_accident_insurance <>", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceGreaterThan(String value) {
            addCriterion("is_accident_insurance >", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("is_accident_insurance >=", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceLessThan(String value) {
            addCriterion("is_accident_insurance <", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceLessThanOrEqualTo(String value) {
            addCriterion("is_accident_insurance <=", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceLike(String value) {
            addCriterion("is_accident_insurance like", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceNotLike(String value) {
            addCriterion("is_accident_insurance not like", value, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceIn(List<String> values) {
            addCriterion("is_accident_insurance in", values, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceNotIn(List<String> values) {
            addCriterion("is_accident_insurance not in", values, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceBetween(String value1, String value2) {
            addCriterion("is_accident_insurance between", value1, value2, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andIsAccidentInsuranceNotBetween(String value1, String value2) {
            addCriterion("is_accident_insurance not between", value1, value2, "isAccidentInsurance");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNull() {
            addCriterion("report_code is null");
            return (Criteria) this;
        }

        public Criteria andReportCodeIsNotNull() {
            addCriterion("report_code is not null");
            return (Criteria) this;
        }

        public Criteria andReportCodeEqualTo(String value) {
            addCriterion("report_code =", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotEqualTo(String value) {
            addCriterion("report_code <>", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThan(String value) {
            addCriterion("report_code >", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeGreaterThanOrEqualTo(String value) {
            addCriterion("report_code >=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThan(String value) {
            addCriterion("report_code <", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLessThanOrEqualTo(String value) {
            addCriterion("report_code <=", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeLike(String value) {
            addCriterion("report_code like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotLike(String value) {
            addCriterion("report_code not like", value, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeIn(List<String> values) {
            addCriterion("report_code in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotIn(List<String> values) {
            addCriterion("report_code not in", values, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeBetween(String value1, String value2) {
            addCriterion("report_code between", value1, value2, "reportCode");
            return (Criteria) this;
        }

        public Criteria andReportCodeNotBetween(String value1, String value2) {
            addCriterion("report_code not between", value1, value2, "reportCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_in
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 29 15:20:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_in
     *
     * @mbggenerated Mon Jun 29 15:20:16 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}