package com.quanroon.atten.reports.entity.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UpWorkerInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public UpWorkerInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNull() {
            addCriterion("platform_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNotNull() {
            addCriterion("platform_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdEqualTo(Integer value) {
            addCriterion("platform_id =", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotEqualTo(Integer value) {
            addCriterion("platform_id <>", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThan(Integer value) {
            addCriterion("platform_id >", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("platform_id >=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThan(Integer value) {
            addCriterion("platform_id <", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThanOrEqualTo(Integer value) {
            addCriterion("platform_id <=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIn(List<Integer> values) {
            addCriterion("platform_id in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotIn(List<Integer> values) {
            addCriterion("platform_id not in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdBetween(Integer value1, Integer value2) {
            addCriterion("platform_id between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotBetween(Integer value1, Integer value2) {
            addCriterion("platform_id not between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("nation is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("nation is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("nation =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("nation <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("nation >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("nation >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("nation <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("nation <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("nation like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("nation not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("nation in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("nation not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("nation between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("nation not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIsNull() {
            addCriterion("current_address is null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIsNotNull() {
            addCriterion("current_address is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressEqualTo(String value) {
            addCriterion("current_address =", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotEqualTo(String value) {
            addCriterion("current_address <>", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressGreaterThan(String value) {
            addCriterion("current_address >", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("current_address >=", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLessThan(String value) {
            addCriterion("current_address <", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLessThanOrEqualTo(String value) {
            addCriterion("current_address <=", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressLike(String value) {
            addCriterion("current_address like", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotLike(String value) {
            addCriterion("current_address not like", value, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressIn(List<String> values) {
            addCriterion("current_address in", values, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotIn(List<String> values) {
            addCriterion("current_address not in", values, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressBetween(String value1, String value2) {
            addCriterion("current_address between", value1, value2, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andCurrentAddressNotBetween(String value1, String value2) {
            addCriterion("current_address not between", value1, value2, "currentAddress");
            return (Criteria) this;
        }

        public Criteria andPoliticalIsNull() {
            addCriterion("political is null");
            return (Criteria) this;
        }

        public Criteria andPoliticalIsNotNull() {
            addCriterion("political is not null");
            return (Criteria) this;
        }

        public Criteria andPoliticalEqualTo(String value) {
            addCriterion("political =", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalNotEqualTo(String value) {
            addCriterion("political <>", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalGreaterThan(String value) {
            addCriterion("political >", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalGreaterThanOrEqualTo(String value) {
            addCriterion("political >=", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalLessThan(String value) {
            addCriterion("political <", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalLessThanOrEqualTo(String value) {
            addCriterion("political <=", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalLike(String value) {
            addCriterion("political like", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalNotLike(String value) {
            addCriterion("political not like", value, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalIn(List<String> values) {
            addCriterion("political in", values, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalNotIn(List<String> values) {
            addCriterion("political not in", values, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalBetween(String value1, String value2) {
            addCriterion("political between", value1, value2, "political");
            return (Criteria) this;
        }

        public Criteria andPoliticalNotBetween(String value1, String value2) {
            addCriterion("political not between", value1, value2, "political");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIsNull() {
            addCriterion("household_register is null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIsNotNull() {
            addCriterion("household_register is not null");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterEqualTo(String value) {
            addCriterion("household_register =", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotEqualTo(String value) {
            addCriterion("household_register <>", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterGreaterThan(String value) {
            addCriterion("household_register >", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterGreaterThanOrEqualTo(String value) {
            addCriterion("household_register >=", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLessThan(String value) {
            addCriterion("household_register <", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLessThanOrEqualTo(String value) {
            addCriterion("household_register <=", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterLike(String value) {
            addCriterion("household_register like", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotLike(String value) {
            addCriterion("household_register not like", value, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterIn(List<String> values) {
            addCriterion("household_register in", values, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotIn(List<String> values) {
            addCriterion("household_register not in", values, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterBetween(String value1, String value2) {
            addCriterion("household_register between", value1, value2, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andHouseholdRegisterNotBetween(String value1, String value2) {
            addCriterion("household_register not between", value1, value2, "householdRegister");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIsNull() {
            addCriterion("education_degree is null");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIsNotNull() {
            addCriterion("education_degree is not null");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeEqualTo(String value) {
            addCriterion("education_degree =", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotEqualTo(String value) {
            addCriterion("education_degree <>", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeGreaterThan(String value) {
            addCriterion("education_degree >", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("education_degree >=", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLessThan(String value) {
            addCriterion("education_degree <", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLessThanOrEqualTo(String value) {
            addCriterion("education_degree <=", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeLike(String value) {
            addCriterion("education_degree like", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotLike(String value) {
            addCriterion("education_degree not like", value, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeIn(List<String> values) {
            addCriterion("education_degree in", values, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotIn(List<String> values) {
            addCriterion("education_degree not in", values, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeBetween(String value1, String value2) {
            addCriterion("education_degree between", value1, value2, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andEducationDegreeNotBetween(String value1, String value2) {
            addCriterion("education_degree not between", value1, value2, "educationDegree");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressIsNull() {
            addCriterion("card_no_address is null");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressIsNotNull() {
            addCriterion("card_no_address is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressEqualTo(String value) {
            addCriterion("card_no_address =", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressNotEqualTo(String value) {
            addCriterion("card_no_address <>", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressGreaterThan(String value) {
            addCriterion("card_no_address >", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressGreaterThanOrEqualTo(String value) {
            addCriterion("card_no_address >=", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressLessThan(String value) {
            addCriterion("card_no_address <", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressLessThanOrEqualTo(String value) {
            addCriterion("card_no_address <=", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressLike(String value) {
            addCriterion("card_no_address like", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressNotLike(String value) {
            addCriterion("card_no_address not like", value, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressIn(List<String> values) {
            addCriterion("card_no_address in", values, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressNotIn(List<String> values) {
            addCriterion("card_no_address not in", values, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressBetween(String value1, String value2) {
            addCriterion("card_no_address between", value1, value2, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoAddressNotBetween(String value1, String value2) {
            addCriterion("card_no_address not between", value1, value2, "cardNoAddress");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateIsNull() {
            addCriterion("card_no_start_date is null");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateIsNotNull() {
            addCriterion("card_no_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateEqualTo(Date value) {
            addCriterion("card_no_start_date =", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateNotEqualTo(Date value) {
            addCriterion("card_no_start_date <>", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateGreaterThan(Date value) {
            addCriterion("card_no_start_date >", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("card_no_start_date >=", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateLessThan(Date value) {
            addCriterion("card_no_start_date <", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateLessThanOrEqualTo(Date value) {
            addCriterion("card_no_start_date <=", value, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateIn(List<Date> values) {
            addCriterion("card_no_start_date in", values, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateNotIn(List<Date> values) {
            addCriterion("card_no_start_date not in", values, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateBetween(Date value1, Date value2) {
            addCriterion("card_no_start_date between", value1, value2, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoStartDateNotBetween(Date value1, Date value2) {
            addCriterion("card_no_start_date not between", value1, value2, "cardNoStartDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateIsNull() {
            addCriterion("card_no_end_date is null");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateIsNotNull() {
            addCriterion("card_no_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateEqualTo(Date value) {
            addCriterion("card_no_end_date =", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateNotEqualTo(Date value) {
            addCriterion("card_no_end_date <>", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateGreaterThan(Date value) {
            addCriterion("card_no_end_date >", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("card_no_end_date >=", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateLessThan(Date value) {
            addCriterion("card_no_end_date <", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateLessThanOrEqualTo(Date value) {
            addCriterion("card_no_end_date <=", value, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateIn(List<Date> values) {
            addCriterion("card_no_end_date in", values, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateNotIn(List<Date> values) {
            addCriterion("card_no_end_date not in", values, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateBetween(Date value1, Date value2) {
            addCriterion("card_no_end_date between", value1, value2, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoEndDateNotBetween(Date value1, Date value2) {
            addCriterion("card_no_end_date not between", value1, value2, "cardNoEndDate");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Integer value) {
            addCriterion("proj_id =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeIsNull() {
            addCriterion("card_no_type is null");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeIsNotNull() {
            addCriterion("card_no_type is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeEqualTo(String value) {
            addCriterion("card_no_type =", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeNotEqualTo(String value) {
            addCriterion("card_no_type <>", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeGreaterThan(String value) {
            addCriterion("card_no_type >", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("card_no_type >=", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeLessThan(String value) {
            addCriterion("card_no_type <", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeLessThanOrEqualTo(String value) {
            addCriterion("card_no_type <=", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeLike(String value) {
            addCriterion("card_no_type like", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeNotLike(String value) {
            addCriterion("card_no_type not like", value, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeIn(List<String> values) {
            addCriterion("card_no_type in", values, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeNotIn(List<String> values) {
            addCriterion("card_no_type not in", values, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeBetween(String value1, String value2) {
            addCriterion("card_no_type between", value1, value2, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoTypeNotBetween(String value1, String value2) {
            addCriterion("card_no_type not between", value1, value2, "cardNoType");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingIsNull() {
            addCriterion("card_no_issuing is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingIsNotNull() {
            addCriterion("card_no_issuing is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingEqualTo(String value) {
            addCriterion("card_no_issuing =", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingNotEqualTo(String value) {
            addCriterion("card_no_issuing <>", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingGreaterThan(String value) {
            addCriterion("card_no_issuing >", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingGreaterThanOrEqualTo(String value) {
            addCriterion("card_no_issuing >=", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingLessThan(String value) {
            addCriterion("card_no_issuing <", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingLessThanOrEqualTo(String value) {
            addCriterion("card_no_issuing <=", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingLike(String value) {
            addCriterion("card_no_issuing like", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingNotLike(String value) {
            addCriterion("card_no_issuing not like", value, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingIn(List<String> values) {
            addCriterion("card_no_issuing in", values, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingNotIn(List<String> values) {
            addCriterion("card_no_issuing not in", values, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingBetween(String value1, String value2) {
            addCriterion("card_no_issuing between", value1, value2, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andCardNoIssuingNotBetween(String value1, String value2) {
            addCriterion("card_no_issuing not between", value1, value2, "cardNoIssuing");
            return (Criteria) this;
        }

        public Criteria andHealthyIsNull() {
            addCriterion("healthy is null");
            return (Criteria) this;
        }

        public Criteria andHealthyIsNotNull() {
            addCriterion("healthy is not null");
            return (Criteria) this;
        }

        public Criteria andHealthyEqualTo(String value) {
            addCriterion("healthy =", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyNotEqualTo(String value) {
            addCriterion("healthy <>", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyGreaterThan(String value) {
            addCriterion("healthy >", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyGreaterThanOrEqualTo(String value) {
            addCriterion("healthy >=", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyLessThan(String value) {
            addCriterion("healthy <", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyLessThanOrEqualTo(String value) {
            addCriterion("healthy <=", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyLike(String value) {
            addCriterion("healthy like", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyNotLike(String value) {
            addCriterion("healthy not like", value, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyIn(List<String> values) {
            addCriterion("healthy in", values, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyNotIn(List<String> values) {
            addCriterion("healthy not in", values, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyBetween(String value1, String value2) {
            addCriterion("healthy between", value1, value2, "healthy");
            return (Criteria) this;
        }

        public Criteria andHealthyNotBetween(String value1, String value2) {
            addCriterion("healthy not between", value1, value2, "healthy");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesIsNull() {
            addCriterion("is_diseases is null");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesIsNotNull() {
            addCriterion("is_diseases is not null");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesEqualTo(String value) {
            addCriterion("is_diseases =", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesNotEqualTo(String value) {
            addCriterion("is_diseases <>", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesGreaterThan(String value) {
            addCriterion("is_diseases >", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesGreaterThanOrEqualTo(String value) {
            addCriterion("is_diseases >=", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesLessThan(String value) {
            addCriterion("is_diseases <", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesLessThanOrEqualTo(String value) {
            addCriterion("is_diseases <=", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesLike(String value) {
            addCriterion("is_diseases like", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesNotLike(String value) {
            addCriterion("is_diseases not like", value, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesIn(List<String> values) {
            addCriterion("is_diseases in", values, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesNotIn(List<String> values) {
            addCriterion("is_diseases not in", values, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesBetween(String value1, String value2) {
            addCriterion("is_diseases between", value1, value2, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andIsDiseasesNotBetween(String value1, String value2) {
            addCriterion("is_diseases not between", value1, value2, "isDiseases");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 29 15:20:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}