package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpCompanyIn;
import com.quanroon.atten.reports.entity.example.UpCompanyInExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
public interface UpCompanyInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int countByExample(UpCompanyInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int deleteByExample(UpCompanyInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int insert(UpCompanyIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int insertSelective(UpCompanyIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    List<UpCompanyIn> selectByExampleWithRowbounds(UpCompanyInExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    UpCompanyIn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    List<UpCompanyIn> selectByExample(UpCompanyInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpCompanyIn record, @Param("example") UpCompanyInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_in
     *
     * @mbggenerated Mon Jun 29 14:58:45 CST 2020
     */
    int updateByExample(@Param("record") UpCompanyIn record, @Param("example") UpCompanyInExample example);

    /**
     * 查询参建单位信息
     * @param companyId
     * @return
     */
    UpCompanyIn selectByCompanyId(@Param("companyId")Integer companyId);

    /**
     * 存储上报成功后的responseCode
     * @param companyId
     * @return
     */
    int updateByCompanyId(@Param("companyId")Integer companyId,@Param("code")String code);
}