package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpCompanyInfo;
import com.quanroon.atten.reports.entity.example.UpCompanyInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UpCompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int countByExample(UpCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int deleteByExample(UpCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int insert(UpCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int insertSelective(UpCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    List<UpCompanyInfo> selectByExampleWithRowbounds(UpCompanyInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    List<UpCompanyInfo> selectByExample(UpCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    UpCompanyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpCompanyInfo record, @Param("example") UpCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int updateByExample(@Param("record") UpCompanyInfo record, @Param("example") UpCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int updateByPrimaryKeySelective(UpCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    int updateByPrimaryKey(UpCompanyInfo record);
}