package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpDeviceInfo;
import com.quanroon.atten.reports.entity.example.UpDeviceInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpDeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int countByExample(UpDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int deleteByExample(UpDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int insert(UpDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int insertSelective(UpDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    List<UpDeviceInfo> selectByExampleWithRowbounds(UpDeviceInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    List<UpDeviceInfo> selectByExample(UpDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    UpDeviceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpDeviceInfo record, @Param("example") UpDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int updateByExample(@Param("record") UpDeviceInfo record, @Param("example") UpDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int updateByPrimaryKeySelective(UpDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    int updateByPrimaryKey(UpDeviceInfo record);
}