package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpDictInfo;

import java.util.List;

import com.quanroon.atten.reports.entity.example.UpDictInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UpDictInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int countByExample(UpDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int deleteByExample(UpDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int insert(UpDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int insertSelective(UpDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    List<UpDictInfo> selectByExampleWithRowbounds(UpDictInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    List<UpDictInfo> selectByExample(UpDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    UpDictInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpDictInfo record, @Param("example") UpDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int updateByExample(@Param("record") UpDictInfo record, @Param("example") UpDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int updateByPrimaryKeySelective(UpDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dict_info
     *
     * @mbggenerated Wed Aug 05 11:01:25 CST 2020
     */
    int updateByPrimaryKey(UpDictInfo record);
}