package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpDynamicField;
import com.quanroon.atten.reports.entity.example.UpDynamicFieldExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UpDynamicFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int countByExample(UpDynamicFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int deleteByExample(UpDynamicFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int insert(UpDynamicField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int insertSelective(UpDynamicField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    List<UpDynamicField> selectByExampleWithRowbounds(UpDynamicFieldExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    List<UpDynamicField> selectByExample(UpDynamicFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    UpDynamicField selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpDynamicField record, @Param("example") UpDynamicFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int updateByExample(@Param("record") UpDynamicField record, @Param("example") UpDynamicFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int updateByPrimaryKeySelective(UpDynamicField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    int updateByPrimaryKey(UpDynamicField record);
}