package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpFile;
import com.quanroon.atten.reports.entity.example.UpFileExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
public interface UpFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int countByExample(UpFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int deleteByExample(UpFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int insert(UpFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int insertSelective(UpFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    List<UpFile> selectByExampleWithRowbounds(UpFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    List<UpFile> selectByExample(UpFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    UpFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpFile record, @Param("example") UpFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int updateByExample(@Param("record") UpFile record, @Param("example") UpFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int updateByPrimaryKeySelective(UpFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_file
     *
     * @mbggenerated Mon Jun 29 15:03:37 CST 2020
     */
    int updateByPrimaryKey(UpFile record);

    List<UpFile> selectByTableNameAndTableId(@Param("tableName") String tableName, @Param("tableId") Integer tableId);

    /**
     * 获取指定客户id的图片
     * @param tableId
     * @param tableModule
     * @return
     */
    UpFile selectByTableIdAndTableModule(@Param("tableId") Integer tableId,@Param("tableModule") String tableModule);

    UpFile selectByTableNameAndTableIdAndModule(@Param("tableName") String tableName, @Param("tableId") Integer tableId,@Param("tableModule") String tableModule);
}