package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpGroupInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuGroupDTO;
import com.quanroon.atten.reports.entity.dto.UpGroupInfoDTO;
import com.quanroon.atten.reports.entity.example.UpGroupInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UpGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int countByExample(UpGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int deleteByExample(UpGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int insert(UpGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int insertSelective(UpGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    List<UpGroupInfo> selectByExampleWithRowbounds(UpGroupInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    List<UpGroupInfo> selectByExample(UpGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    UpGroupInfo selectByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpGroupInfo record, @Param("example") UpGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int updateByExample(@Param("record") UpGroupInfo record, @Param("example") UpGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int updateByPrimaryKeySelective(UpGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_group_info
     *
     * @mbggenerated Mon Jun 29 15:19:03 CST 2020
     */
    int updateByPrimaryKey(UpGroupInfo record);

    /**
     * 查询蚌埠上报班组信息数据
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-09-01 11:17
     */
    UpBengbuGroupDTO seletBengBuGroupInfo(Integer id);
}