package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpParams;
import com.quanroon.atten.reports.entity.example.UpParamsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int countByExample(UpParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int deleteByExample(UpParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int insert(UpParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int insertSelective(UpParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    List<UpParams> selectByExampleWithRowbounds(UpParamsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    List<UpParams> selectByExample(UpParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    UpParams selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpParams record, @Param("example") UpParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int updateByExample(@Param("record") UpParams record, @Param("example") UpParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int updateByPrimaryKeySelective(UpParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    int updateByPrimaryKey(UpParams record);

    UpParams selectByProjId(@Param("projId") Integer projId);

    /**
     * 根据项目信息的项目id查询是否有对应的配置
     * @param projId
     * @return
     */
    List<UpParams> selectUpParamsAndProjInfoByProjId(@Param("projId") Integer projId);
}