package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpPayrollInfo;
import com.quanroon.atten.reports.entity.example.UpPayrollInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpPayrollInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int countByExample(UpPayrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int deleteByExample(UpPayrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int insert(UpPayrollInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int insertSelective(UpPayrollInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    List<UpPayrollInfo> selectByExampleWithRowbounds(UpPayrollInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    List<UpPayrollInfo> selectByExample(UpPayrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    UpPayrollInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpPayrollInfo record, @Param("example") UpPayrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int updateByExample(@Param("record") UpPayrollInfo record, @Param("example") UpPayrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int updateByPrimaryKeySelective(UpPayrollInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    int updateByPrimaryKey(UpPayrollInfo record);

    /**
     * 工资单明细查询工资单信息
     * @param id
     * @return
     */
    UpPayrollInfo selectPayrollByDetailId(Integer id);
}