package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpPayrollDetailInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuPayRollDTO;
import com.quanroon.atten.reports.entity.example.UpPayrollDetailInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpPayrollDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int countByExample(UpPayrollDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int deleteByExample(UpPayrollDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int insert(UpPayrollDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int insertSelective(UpPayrollDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    List<UpPayrollDetailInfo> selectByExampleWithRowbounds(UpPayrollDetailInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    List<UpPayrollDetailInfo> selectByExample(UpPayrollDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    UpPayrollDetailInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpPayrollDetailInfo record, @Param("example") UpPayrollDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int updateByExample(@Param("record") UpPayrollDetailInfo record, @Param("example") UpPayrollDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int updateByPrimaryKeySelective(UpPayrollDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    int updateByPrimaryKey(UpPayrollDetailInfo record);
    
    /**
     * 查询当前劳工的工资单信息
     * @auther: 罗森林
     * @param:
     * @return: 
     * @date: 2020-09-02 14:44
     */
    UpBengbuPayRollDTO selectBengBuPayRollInfo(Integer id);
}