package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpPlatformAuth;
import com.quanroon.atten.reports.entity.example.UpPlatmeAuthExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
public interface UpPlatmeAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int countByExample(UpPlatmeAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int deleteByExample(UpPlatmeAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int insert(UpPlatformAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int insertSelective(UpPlatformAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    List<UpPlatformAuth> selectByExampleWithRowbounds(UpPlatmeAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    List<UpPlatformAuth> selectByExample(UpPlatmeAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpPlatformAuth record, @Param("example") UpPlatmeAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_platme_auth
     *
     * @mbggenerated Mon Jun 29 16:26:17 CST 2020
     */
    int updateByExample(@Param("record") UpPlatformAuth record, @Param("example") UpPlatmeAuthExample example);
}