package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpProjectCertificate;
import com.quanroon.atten.reports.entity.example.UpProjectCertificateExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
public interface UpProjectCertificateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int countByExample(UpProjectCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int deleteByExample(UpProjectCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int insert(UpProjectCertificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int insertSelective(UpProjectCertificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    List<UpProjectCertificate> selectByExampleWithRowbounds(UpProjectCertificateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    List<UpProjectCertificate> selectByExample(UpProjectCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpProjectCertificate record, @Param("example") UpProjectCertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_certificate
     *
     * @mbggenerated Mon Jun 29 15:05:42 CST 2020
     */
    int updateByExample(@Param("record") UpProjectCertificate record, @Param("example") UpProjectCertificateExample example);

    /**
     * 批量保存施工许可信息
     * @param certificateList
     * @return
     */
    int batchInsertUpProjectCertificate(@Param("list") List<UpProjectCertificate> certificateList);

    /**
     * 批量修改施工许可信息
     * @param certificateList
     * @return
     */
    int batchUpdateUpProjectCertificate(@Param("list") List<UpProjectCertificate> certificateList);


    /**
     * 根据项目id查询施工许可
     * @param projId
     * @return
     */
    UpProjectCertificate selectByProjId(@Param("projId")Integer projId);
}