package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpProjectInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuProjDTO;
import com.quanroon.atten.reports.entity.example.UpProjectInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface UpProjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int countByExample(UpProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int deleteByExample(UpProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int insert(UpProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int insertSelective(UpProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    List<UpProjectInfo> selectByExampleWithRowbounds(UpProjectInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    List<UpProjectInfo> selectByExample(UpProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    UpProjectInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpProjectInfo record, @Param("example") UpProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int updateByExample(@Param("record") UpProjectInfo record, @Param("example") UpProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int updateByPrimaryKeySelective(UpProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_info
     *
     * @mbggenerated Tue Jun 30 17:17:38 CST 2020
     */
    int updateByPrimaryKey(UpProjectInfo record);
    /**
     * 查询蚌埠上报项目信息
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-08-28 10:15
     */
    UpBengbuProjDTO selectBengbuProjInfo(Integer id);
}