package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpProjectAuth;
import com.quanroon.atten.reports.entity.example.UpProjectAuthExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface UpProjectAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int countByExample(UpProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int deleteByExample(UpProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int insert(UpProjectAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int insertSelective(UpProjectAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    List<UpProjectAuth> selectByExampleWithRowbounds(UpProjectAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    List<UpProjectAuth> selectByExample(UpProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpProjectAuth record, @Param("example") UpProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    int updateByExample(@Param("record") UpProjectAuth record, @Param("example") UpProjectAuthExample example);
}