package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpRecord;
import com.quanroon.atten.reports.entity.example.UpRecordExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
public interface UpRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int countByExample(UpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int deleteByExample(UpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int insert(UpRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int insertSelective(UpRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    List<UpRecord> selectByExampleWithRowbounds(UpRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    List<UpRecord> selectByExample(UpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpRecord record, @Param("example") UpRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    int updateByExample(@Param("record") UpRecord record, @Param("example") UpRecordExample example);

    /**
     * 对离场业务进行状态回滚操作
     * @param tableName
     * @param dataId
     * @return
     */
    int updateDynamicStatusByTableNameAndId(@Param("tableName") String tableName, @Param("dataId") Integer dataId);


}