package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpCompanyInfo;
import com.quanroon.atten.reports.entity.UpSalaryInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuSalaryInfoDTO;
import com.quanroon.atten.reports.entity.example.UpSalaryInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpSalaryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int countByExample(UpSalaryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int deleteByExample(UpSalaryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int insert(UpSalaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int insertSelective(UpSalaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    List<UpSalaryInfo> selectByExampleWithRowbounds(UpSalaryInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    List<UpSalaryInfo> selectByExample(UpSalaryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    UpSalaryInfo selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpSalaryInfo record, @Param("example") UpSalaryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int updateByExample(@Param("record") UpSalaryInfo record, @Param("example") UpSalaryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int updateByPrimaryKeySelective(UpSalaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_salary_info
     *
     * @mbggenerated Mon Jun 29 15:17:49 CST 2020
     */
    int updateByPrimaryKey(UpSalaryInfo record);

    /**
     * 由工资专户到账信息查询专户信息
     * @param id
     * @return
     */
    UpSalaryInfo selectSalaryInfoByArriveId(Integer id);
    /**
     * 通过项目id和单位id查询专户信息
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-08-31 16:39
     */
    UpBengbuSalaryInfoDTO selectCompanySalaryInfo(UpCompanyInfo upCompanyInfo);
    /**
     * 通过项目查询工资专户信息
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-09-09 19:36
     */
    UpSalaryInfo selectByProjIdPrimaryKey(Integer projId);
}