package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpWorkerSignlogInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuSignlogDTO;
import com.quanroon.atten.reports.entity.example.UpWorkerSignlogInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
public interface UpWorkerSignlogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int countByExample(UpWorkerSignlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int deleteByExample(UpWorkerSignlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int insert(UpWorkerSignlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int insertSelective(UpWorkerSignlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    List<UpWorkerSignlogInfo> selectByExampleWithRowbounds(UpWorkerSignlogInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    List<UpWorkerSignlogInfo> selectByExample(UpWorkerSignlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    UpWorkerSignlogInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpWorkerSignlogInfo record, @Param("example") UpWorkerSignlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int updateByExample(@Param("record") UpWorkerSignlogInfo record, @Param("example") UpWorkerSignlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int updateByPrimaryKeySelective(UpWorkerSignlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    int updateByPrimaryKey(UpWorkerSignlogInfo record);

    /**
     * 查询蚌埠市上报考勤数据
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-09-02 16:37
     */
    UpBengbuSignlogDTO selectBengbuSignLogInfo(Integer projId);
}