package com.quanroon.atten.reports.dao;

import com.quanroon.atten.reports.entity.UpWorkerInfo;
import com.quanroon.atten.reports.entity.dto.UpBengbuWorkerInDTO;
import com.quanroon.atten.reports.entity.example.UpWorkerInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

public interface UpWorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int countByExample(UpWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int deleteByExample(UpWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int insert(UpWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int insertSelective(UpWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    List<UpWorkerInfo> selectByExampleWithRowbounds(UpWorkerInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    List<UpWorkerInfo> selectByExample(UpWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    UpWorkerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpWorkerInfo record, @Param("example") UpWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int updateByExample(@Param("record") UpWorkerInfo record, @Param("example") UpWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int updateByPrimaryKeySelective(UpWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_worker_info
     *
     * @mbggenerated Mon Jun 29 15:20:45 CST 2020
     */
    int updateByPrimaryKey(UpWorkerInfo record);
    /**
     * 查询蚌埠上报劳工信息
     * @auther: 罗森林
     * @param:
     * @return:
     * @date: 2020-09-01 14:04
     */
    UpBengbuWorkerInDTO selectBengBuWorkerInfo(Integer id);
}