package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.quanroon.atten.commons.utils.DateUtils;
import com.quanroon.atten.commons.utils.StringUtils;
import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import com.quanroon.atten.reports.entity.dto.UpCompanyInfoDTO;
import com.quanroon.atten.reports.entity.dto.UpWorkerInDTO;
import lombok.Data;

/**
 * Table: up_company_info
 */
@Data
@TableEntity(ReportConstant.UP_COMPANY_INFO)
public class UpCompanyInfo implements Serializable, EntityInterface<UpCompanyInfo> {
    /**
     * 主码
     *
     * Table:     up_company_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 项目id
     *
     * Table:     up_company_info
     * Column:    proj_id
     * Nullable:  false
     */
    private Integer projId;

    /**
     * 统一社会信用代码
     *
     * Table:     up_company_info
     * Column:    corp_code
     * Nullable:  true
     */
    private String corpCode;

    /**
     * 企业名称
     *
     * Table:     up_company_info
     * Column:    NAME
     * Nullable:  true
     */
    private String name;

    /**
     * 企业类型
     *
     * Table:     up_company_info
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 企业邮箱
     *
     * Table:     up_company_info
     * Column:    email
     * Nullable:  true
     */
    private String email;

    /**
     * 省级编码
     *
     * Table:     up_company_info
     * Column:    province_code
     * Nullable:  true
     */
    private String provinceCode;

    /**
     * 市级编码
     *
     * Table:     up_company_info
     * Column:    city_code
     * Nullable:  true
     */
    private String cityCode;

    /**
     * 区级编码
     *
     * Table:     up_company_info
     * Column:    area_code
     * Nullable:  true
     */
    private String areaCode;

    /**
     * 企业营业地址
     *
     * Table:     up_company_info
     * Column:    address
     * Nullable:  true
     */
    private String address;

    /**
     * 邮政编码
     *
     * Table:     up_company_info
     * Column:    zip_code
     * Nullable:  true
     */
    private String zipCode;

    /**
     * 法人代表
     *
     * Table:     up_company_info
     * Column:    legal_name
     * Nullable:  true
     */
    private String legalName;

    /**
     * 法人电话
     *
     * Table:     up_company_info
     * Column:    legal_phone
     * Nullable:  true
     */
    private String legalPhone;

    /**
     * 法人电话
     *
     * Table:     up_company_info
     * Column:    legal_card
     * Nullable:  true
     */
    private String legalCard;

    /**
     * 企业注册日期
     *
     * Table:     up_company_info
     * Column:    register_date
     * Nullable:  true
     */
    private Date registerDate;

    /**
     * 注册资金
     *
     * Table:     up_company_info
     * Column:    register_amount
     * Nullable:  true
     */
    private BigDecimal registerAmount;

    /**
     * 创建日期
     *
     * Table:     up_company_info
     * Column:    create_date
     * Nullable:  true
     */
    private Date createDate;

    /**
     * 修改时间
     *
     * Table:     up_company_info
     * Column:    update_date
     * Nullable:  true
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_company_info
     *
     * @mbggenerated Mon Jun 29 15:02:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 部分DTO转换Entity时间格式转换
     * @param companyInfoDTO
     */
    public void copyDateFormat(UpCompanyInfoDTO companyInfoDTO) {
        if (StringUtils.isNoneEmpty(companyInfoDTO.getRegisterDate())) {
            this.registerDate = DateUtils.parseDate(companyInfoDTO.getRegisterDate());
        }
    }

    @Override
    public CodeEntity initCodeEntity(Integer projId) {

        return CodeEntity.builder()
                .tableId(id)
                .projId(this.projId).build();
    }
}