package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.util.Date;

import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_device_info
 */
@Data
@TableEntity(ReportConstant.UP_DEVICE_INFO)
public class UpDeviceInfo implements Serializable, EntityInterface<UpDeviceInfo> {
    /**
     * 主码
     *
     * Table:     up_device_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 项目id
     *
     * Table:     up_device_info
     * Column:    proj_id
     * Nullable:  true
     */
    private Integer projId;

    /**
     * 考勤机名称
     *
     * Table:     up_device_info
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * 考勤机IP地址
     *
     * Table:     up_device_info
     * Column:    ip
     * Nullable:  true
     */
    private String ip;

    /**
     * 考勤机IP端口
     *
     * Table:     up_device_info
     * Column:    port
     * Nullable:  true
     */
    private String port;

    /**
     * 进出场类型
     *
     * Table:     up_device_info
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 设备序列号
     *
     * Table:     up_device_info
     * Column:    device_sn
     * Nullable:  true
     */
    private String deviceSn;

    /**
     * 安装位置
     *
     * Table:     up_device_info
     * Column:    address
     * Nullable:  true
     */
    private String address;

    /**
     * 创建时间
     *
     * Table:     up_device_info
     * Column:    create_date
     * Nullable:  true
     */
    private Date createDate;

    /**
     * 更新时间
     *
     * Table:     up_device_info
     * Column:    update_date
     * Nullable:  true
     */
    private Date updateDate;

    /**
     * 上报住建局后返回得唯一编码
     *
     * Table:     up_device_info
     * Column:    report_code
     * Nullable:  true
     */
    private String reportCode;
    /**
     * 是否解绑  1：禁用 0：启动
     */
    private  String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_device_info
     *
     * @mbggenerated Mon Jun 29 15:02:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        return CodeEntity.builder()
                .tableId(id)
                .projId(this.projId).build();
    }
}