package com.quanroon.atten.reports.entity;

import com.quanroon.atten.commons.utils.StringUtils;
import lombok.Data;
import lombok.NonNull;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@RequiredArgsConstructor(staticName = "defineOf")
public class UpDictReport {

    //必填字段缓存时间 单位s
    public final static Integer dictExpire = 24 * 3600;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.id
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.report_city_code
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    @NonNull
    private String reportCityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.report_type
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    @NonNull
    private String reportType = "-1";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.dict_type
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    @NonNull
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.code
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.api_type
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.api_code
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    @NonNull
    private String apiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.create_date
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_dict_report.flag
     *
     * @mbg.generated Fri Jul 24 15:00:43 CST 2020
     */
    private String flag;

    private String otherCode;

    private String otherValue;

    /**
     * 校验查询词典映射集合参数
     * @return
     */
    public boolean validParamsIsEmpty(){
        if(StringUtils.isEmpty(reportCityCode) || StringUtils.isEmpty(reportType)
                || StringUtils.isEmpty(apiCode)){
            return true;
        }
        //默认无平台区分
        if(StringUtils.isEmpty(reportType))
            reportType = "-1";
        return false;
    }
}