package com.quanroon.atten.reports.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * Table: up_dynamic_field
 */
@Data
public class UpDynamicField implements Serializable {

    //必填字段缓存时间 单位s
    public final static Integer fieldsExpire = 2 * 3600;

    /**
     * Table:     up_dynamic_field
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 上报城市编码
     *
     * Table:     up_dynamic_field
     * Column:    city_code
     * Nullable:  true
     */
    private String cityCode;

    /**
     * 上报类型
     *
     * Table:     up_dynamic_field
     * Column:    report_type
     * Nullable:  true
     */
    private String reportType;

    /**
     * 是否支持修改 1:支持 2:不支持
     *
     * Table:     up_dynamic_field
     * Column:    is_modify
     * Nullable:  true
     */
    private String isModify;

    /**
     * 字段名称
     *
     * Table:     up_dynamic_field
     * Column:    field_name
     * Nullable:  true
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_dynamic_field
     *
     * @mbggenerated Mon Jul 06 13:48:22 CST 2020
     */
    private static final long serialVersionUID = 1L;
}