package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.util.Date;

import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_payroll_info
 */
@Data
@TableEntity(ReportConstant.UP_PAYROLL_INFO)
public class UpPayrollInfo implements Serializable, EntityInterface<UpPayrollInfo> {
    /**
     * 主码
     *
     * Table:     up_payroll_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 项目id
     *
     * Table:     up_payroll_info
     * Column:    proj_id
     * Nullable:  true
     */
    private Integer projId;

    /**
     * 企业id
     *
     * Table:     up_payroll_info
     * Column:    company_id
     * Nullable:  true
     */
    private Integer companyId;

    /**
     * 班组id
     *
     * Table:     up_payroll_info
     * Column:    group_id
     * Nullable:  true
     */
    private Integer groupId;

    /**
     * 发放工资的日期
     *
     * Table:     up_payroll_info
     * Column:    grant_salary_date
     * Nullable:  true
     */
    private Date grantSalaryDate;

    /**
     * 发放状态
     *
     * Table:     up_payroll_info
     * Column:    grant_status
     * Nullable:  true
     */
    private String grantStatus;

    /**
     * 财务确认标志
     *
     * Table:     up_payroll_info
     * Column:    confirm_mark
     * Nullable:  true
     */
    private String confirmMark;

    /**
     * 上报住建局后返回的唯一编码
     *
     * Table:     up_payroll_info
     * Column:    report_code
     * Nullable:  true
     */
    private String reportCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_payroll_info
     *
     * @mbggenerated Mon Jun 29 15:05:03 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        return CodeEntity.builder()
                .tableId(id)
                .projId(this.projId).build();
    }
}