package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_payroll_detail_info
 */
@Data
@TableEntity(ReportConstant.UP_PAYROLL_DETAIL_INFO)
public class UpPayrollDetailInfo implements Serializable, EntityInterface<UpPayrollDetailInfo> {
    /**
     * 主码
     *
     * Table:     up_payroll_detail_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 工资单表主键id
     *
     * Table:     up_payroll_detail_info
     * Column:    salary_id
     * Nullable:  true
     */
    private Integer salaryId;

    /**
     * 劳工id
     *
     * Table:     up_payroll_detail_info
     * Column:    worker_id
     * Nullable:  true
     */
    private Integer workerId;

    /**
     * 当月出勤天数
     *
     * Table:     up_payroll_detail_info
     * Column:    attendance_days
     * Nullable:  true
     */
    private Integer attendanceDays;

    /**
     * 应发金额
     *
     * Table:     up_payroll_detail_info
     * Column:    payable_money
     * Nullable:  true
     */
    private BigDecimal payableMoney;

    /**
     * 实发金额
     *
     * Table:     up_payroll_detail_info
     * Column:    paid_money
     * Nullable:  true
     */
    private BigDecimal paidMoney;

    /**
     * 个人核对标志
     *
     * Table:     up_payroll_detail_info
     * Column:    check_mark
     * Nullable:  true
     */
    private String checkMark;

    /**
     * 是否为补发
     *
     * Table:     up_payroll_detail_info
     * Column:    is_reissue
     * Nullable:  true
     */
    private String isReissue;

    /**
     * 补发月份（如果为补发必填）
     *
     * Table:     up_payroll_detail_info
     * Column:    reissue_month
     * Nullable:  true
     */
    private Date reissueMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_payroll_detail_info
     *
     * @mbggenerated Mon Jun 29 15:04:37 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        return CodeEntity.builder()
                .tableId(id)
                .projId(projId).build();
    }
}