package com.quanroon.atten.reports.entity;

import java.io.Serializable;

import com.quanroon.atten.commons.utils.StringUtils;
import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_params
 */
@Data
@TableEntity(ReportConstant.UP_PARAMS)
public class UpParams implements Serializable, EntityInterface<UpParams> {
    /**
     * 主码
     *
     * Table:     up_params
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 项目id
     *
     * Table:     up_params
     * Column:    proj_id
     * Nullable:  false
     */
    private Integer projId;

    /**
     * 账号
     *
     * Table:     up_params
     * Column:    account
     * Nullable:  true
     */
    private String account;

    /**
     * 密码
     *
     * Table:     up_params
     * Column:    password
     * Nullable:  true
     */
    private String password;

    /**
     * 项目编号
     *
     * Table:     up_params
     * Column:    project_code
     * Nullable:  true
     */
    private String projectCode;

    /**
     * 授权账号
     *
     * Table:     up_params
     * Column:    key
     * Nullable:  true
     */
    private String key;

    /**
     * 授权密钥
     *
     * Table:     up_params
     * Column:    secret
     * Nullable:  true
     */
    private String secret;

    /**
     * 采集key
     *
     * Table:     up_params
     * Column:    collect_key
     * Nullable:  true
     */
    private String collectKey;

    /**
     * 采集密钥
     *
     * Table:     up_params
     * Column:    collect_secret
     * Nullable:  true
     */
    private String collectSecret;

    /**
     * 厂家识别码
     *
     * Table:     up_params
     * Column:    app_token
     * Nullable:  true
     */
    private String appToken;

    /**
     * 上报省
     *
     * Table:     up_params
     * Column:    up_province
     * Nullable:  true
     */
    private String upProvince;

    /**
     * 上报市
     *
     * Table:     up_params
     * Column:    up_city
     * Nullable:  true
     */
    private String upCity;

    /**
     * 上报县
     *
     * Table:     up_params
     * Column:    up_area
     * Nullable:  true
     */
    private String upArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_params
     *
     * @mbggenerated Mon Jun 29 15:04:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        //配置上报，实际为项目新增上报，因此tabelId应该为项目id
        return CodeEntity.builder()
                .tableId(this.projId)
                .projId(this.projId).build();
    }
}