package com.quanroon.atten.reports.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: up_platform_auth
 */
@Data
public class UpPlatformAuth implements Serializable {
    /**启用*/
    public static final String STATUS_OPEN = "0";
    /**禁用*/
    public static final String STATUS_STOP = "1";
    public static final String CACHE_PREFIX = "reportApi:company";
    public static final String FIELD_PREFIX = ":dynamicField";
    /**
     * 主键
     *
     * Table:     up_platform_auth
     * Column:    company_id
     * Nullable:  false
     */
    private Integer companyId;

    /**
     * 公司名称/平台名称
     *
     * Table:     up_platform_auth
     * Column:    company_name
     * Nullable:  true
     */
    private String companyName;

    /**
     * appid
     *
     * Table:     up_platform_auth
     * Column:    app_id
     * Nullable:  true
     */
    private String appId;

    /**
     * appkey
     *
     * Table:     up_platform_auth
     * Column:    app_key
     * Nullable:  true
     */
    private String appKey;

    /**
     * 状态 0：可用 1：禁用
     *
     * Table:     up_platform_auth
     * Column:    status
     * Nullable:  true
     */
    private String status;

    /**
     * 备注
     *
     * Table:     up_platform_auth
     * Column:    remark
     * Nullable:  true
     */
    private String remark;

    /**
     * Table:     up_platform_auth
     * Column:    create_date
     * Nullable:  true
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_platform_auth
     *
     * @mbggenerated Tue Jun 30 15:12:47 CST 2020
     */
    private static final long serialVersionUID = 1L;
}