package com.quanroon.atten.reports.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * Table: up_project_auth
 */
@Data
public class UpProjectAuth implements Serializable {


    /**
     * 项目表id
     *
     * Table:     up_project_auth
     * Column:    proj_id
     * Nullable:  false
     */
    private Integer projId;

    /**
     * 项目秘钥id
     *
     * Table:     up_project_auth
     * Column:    auth_id
     * Nullable:  true
     */
    private String authId;

    /**
     * 项目秘钥
     *
     * Table:     up_project_auth
     * Column:    auth_key
     * Nullable:  true
     */
    private String authKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_project_auth
     *
     * @mbggenerated Tue Jun 30 17:36:37 CST 2020
     */
    private static final long serialVersionUID = 1L;
}