package com.quanroon.atten.reports.entity;

import com.quanroon.atten.commons.utils.DateUtils;
import com.quanroon.atten.reports.common.EnumsInterface;
import com.quanroon.atten.reports.common.RecordStatus;
import com.quanroon.atten.reports.common.RecordType;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: up_record
 */
@Data
@NoArgsConstructor
public class UpRecord implements Serializable {

    public UpRecord(String type) {
        this.type = type;
    }

    /**
     * 1:上报中 2:上报成功 3:上报失败
     *
     * Table:     up_record
     * Column:    status
     * Nullable:  true
     */
    private String status;

    /**
     * 上报结果
     *
     * Table:     up_record
     * Column:    result
     * Nullable:  true
     */
    private String result;

    /**
     * 上报类型
     *
     * Table:     up_record
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 上报表名
     *
     * Table:     up_record
     * Column:    table_name
     * Nullable:  true
     */
    private String tableName;

    /**
     * 上报对应表id
     *
     * Table:     up_record
     * Column:    table_id
     * Nullable:  true
     */
    private String tableId;

    /**
     * 1真实上报,2虚假上报
     *
     * Table:     up_record
     * Column:    is_real_report
     * Nullable:  true
     */
    private String isRealReport;

    /**
     * 上报唯一编码
     *
     * Table:     up_record
     * Column:    request_code
     * Nullable:  true
     */
    private String requestCode;

    /**
     * 上报时间
     *
     * Table:     up_record
     * Column:    report_date
     * Nullable:  true
     */
    private Date reportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_record
     *
     * @mbggenerated Mon Jun 29 15:17:07 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /** 模板*/
    private static String PRINT_FORMAT = "==> 上报结果反馈,请求编码requestCode：%s,类型type：%s,动作isRealReport：%s,状态status：%s,结果result：%s,消费时间reportDate：%s";

    /**
     * 打印上报结果
     * @author quanroon.ysq
     * @date 2020.08.06 13:53:22
     * @return
     */
    public String printReportResult(){

        String isReal = isRealReport + "[" + EnumsInterface.getEnumsMessage(RecordType.class, isRealReport)+"]";
        String reportStatus = status + "[" + EnumsInterface.getEnumsMessage(RecordStatus.class, status) + "]";

        return String.format(PRINT_FORMAT, requestCode, type, isReal, reportStatus, result, DateUtils.formatDateTime(reportDate));
    }
}