package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_salary_arrive
 */
@Data
@TableEntity(ReportConstant.UP_SALARY_ARRIVE)
public class UpSalaryArrive implements Serializable, EntityInterface<UpSalaryArrive> {

    /**
     * 主码
     *
     * Table:     up_salary_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 工资专户表id
     *
     * Table:     up_salary_arrive
     * Column:    salary_account_id
     * Nullable:  false
     */
    private Integer salaryAccountId;

    /**
     * 建设单位拨款到帐金额
     *
     * Table:     up_salary_arrive
     * Column:    amount_received
     * Nullable:  true
     */
    private BigDecimal amountReceived;

    /**
     * 建设单位拨款到帐时间
     *
     * Table:     up_salary_arrive
     * Column:    amount_date
     * Nullable:  true
     */
    private Date amountDate;

    /**
     * 工资专用账户余额
     *
     * Table:     up_salary_arrive
     * Column:    remaining_wages
     * Nullable:  true
     */
    private BigDecimal remainingWages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_salary_arrive
     *
     * @mbggenerated Mon Jun 29 15:17:26 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        return CodeEntity.builder()
                .tableId(id)
                .projId(projId).build();
    }
}