package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Table: up_worker_exp
 */
@Data
public class UpWorkerExp implements Serializable {
    /**
     * 劳工id
     *
     * Table:     up_worker_exp
     * Column:    worker_id
     * Nullable:  false
     */
    private Integer workerId;

    /**
     * 证书种类
     *
     * Table:     up_worker_exp
     * Column:    certificate_kind
     * Nullable:  true
     */
    private String certificateKind;

    /**
     * 证书类型
     *
     * Table:     up_worker_exp
     * Column:    certificate_type
     * Nullable:  true
     */
    private String certificateType;

    /**
     * 证书等级
     *
     * Table:     up_worker_exp
     * Column:    certificate_grade
     * Nullable:  true
     */
    private String certificateGrade;

    /**
     * 证书编号
     *
     * Table:     up_worker_exp
     * Column:    certificate_number
     * Nullable:  true
     */
    private String certificateNumber;

    /**
     * 证书名称
     *
     * Table:     up_worker_exp
     * Column:    certificate_name
     * Nullable:  true
     */
    private String certificateName;

    /**
     * 证书有效时间
     *
     * Table:     up_worker_exp
     * Column:    certificate_start_date
     * Nullable:  true
     */
    private Date certificateStartDate;

    /**
     * 证书到期时间
     *
     * Table:     up_worker_exp
     * Column:    certificate_end_date
     * Nullable:  true
     */
    private Date certificateEndDate;

    /**
     * 发证机关
     *
     * Table:     up_worker_exp
     * Column:    certificate_issuing
     * Nullable:  true
     */
    private String certificateIssuing;

    /**
     * 资质证书状态
     *
     * Table:     up_worker_exp
     * Column:    certificate_status
     * Nullable:  true
     */
    private String certificateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_exp
     *
     * @mbggenerated Mon Jun 29 15:18:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

}