package com.quanroon.atten.reports.entity;

import java.io.Serializable;
import java.util.Date;

import com.quanroon.atten.reports.common.ReportConstant;
import com.quanroon.atten.reports.entity.base.CodeEntity;
import com.quanroon.atten.reports.entity.base.EntityInterface;
import com.quanroon.atten.reports.entity.base.TableEntity;
import lombok.Data;

/**
 * Table: up_worker_signlog_info
 */
@Data
@TableEntity(ReportConstant.UP_WORKER_SIGNLOG_INFO)
public class UpWorkerSignlogInfo implements Serializable, EntityInterface<UpWorkerSignlogInfo> {
    /**
     * 主码
     *
     * Table:     up_worker_signlog_info
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 项目id
     *
     * Table:     up_worker_signlog_info
     * Column:    proj_id
     * Nullable:  true
     */
    private Integer projId;

    /**
     * 劳工id
     *
     * Table:     up_worker_signlog_info
     * Column:    worker_id
     * Nullable:  true
     */
    private Integer workerId;

    /**
     * 设备sn
     *
     * Table:     up_worker_signlog_info
     * Column:    device_sn
     * Nullable:  true
     */
    private String deviceSn;

    /**
     * 考勤时间
     *
     * Table:     up_worker_signlog_info
     * Column:    time
     * Nullable:  true
     */
    private Date time;

    /**
     * 考勤进出方向
     *
     * Table:     up_worker_signlog_info
     * Column:    direction
     * Nullable:  true
     */
    private String direction;

    /**
     * 考勤类型
     *
     * Table:     up_worker_signlog_info
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 考勤相似度
     *
     * Table:     up_worker_signlog_info
     * Column:    similar
     * Nullable:  true
     */
    private Double similar;

    /**
     * 经度
     *
     * Table:     up_worker_signlog_info
     * Column:    lat
     * Nullable:  true
     */
    private Double lat;

    /**
     * 纬度
     *
     * Table:     up_worker_signlog_info
     * Column:    lgt
     * Nullable:  true
     */
    private Double lgt;

    /**
     * 上报是否成功
     *
     * Table:     up_worker_signlog_info
     * Column:    report_flag
     * Nullable:  true
     */
    private String reportFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_worker_signlog_info
     *
     * @mbggenerated Mon Jun 29 15:21:06 CST 2020
     */
    private static final long serialVersionUID = 1L;

    @Override
    public CodeEntity initCodeEntity(Integer projId) {
        return CodeEntity.builder()
                .tableId(id)
                .projId(this.projId).build();
    }
}